"""Bilingual strings EN / Tamil"""

STRINGS = {
    'en': {
        'app_name':       "BRO'S LED Controller",
        'company':        "BRO'S Engineering Solution Pvt.Ltd.",
        'tagline':        'Three Friends. One Vision. Endless Innovation.',
        'login':          'Login',
        'signup':         'Sign Up',
        'username':       'Username',
        'password':       'Password',
        'confirm_pass':   'Confirm Password',
        'logout':         'Logout',
        'home':           'Home',
        'menu':           'Menu',
        'display':        'Display',
        'settings':       'Settings',
        'tutorial':       'Tutorial',
        'send_board':     'Send to Board',
        'scan':           'Scan & Connect',
        'save':           'Save',
        'cancel':         'Cancel',
        'add_item':       'Add Item',
        'edit':           'Edit',
        'delete':         'Delete',
        'send_item':      'Send',
        'brightness':     'Brightness',
        'date_time':      'Date & Time',
        'clock':          'Clock on Display',
        'theme':          'App Theme',
        'language':       'Language',
        'ip_address':     'Board IP Address',
        'connect':        'Connect',
        'disconnect':     'Disconnect',
        'name':           'Item Name',
        'price':          'Price (₹)',
        'category':       'Category',
        'welcome':        'Welcome',
        'connected':      '🟢 Connected',
        'not_connected':  '⚪ Not Connected',
        'sent_ok':        'Sent to Board!',
        'no_board':       '❌ Board not connected',
        'scroll_speed':   'Scroll Speed',
        'scroll_dir':     'Scroll Direction',
        'text_color':     'Text Color',
        'bg_color':       'Background',
        'text_msg':       'Display Message',
        'quick_msgs':     'Quick Messages',
        'preview':        'Preview',
    },
    'ta': {
        'app_name':       'BRO\'S LED கட்டுப்பாட்டி',
        'company':        'BRO\'S எஞ்சினியரிங் சொல்யூஷன் Pvt.Ltd.',
        'tagline':        'மூன்று நண்பர்கள். ஒரு லட்சியம். முடிவற்ற கண்டுபிடிப்பு.',
        'login':          'உள்நுழை',
        'signup':         'பதிவு செய்',
        'username':       'பயனர் பெயர்',
        'password':       'கடவுச்சொல்',
        'confirm_pass':   'கடவுச்சொல் உறுதி',
        'logout':         'வெளியேறு',
        'home':           'முகப்பு',
        'menu':           'மெனு',
        'display':        'திரை',
        'settings':       'அமைப்புகள்',
        'tutorial':       'கற்றுக்கொள்',
        'send_board':     'போர்டுக்கு அனுப்பு',
        'scan':           'கண்டுபிடி',
        'save':           'சேமி',
        'cancel':         'ரத்து',
        'add_item':       'சேர்',
        'edit':           'திருத்து',
        'delete':         'நீக்கு',
        'send_item':      'அனுப்பு',
        'brightness':     'ஒளி அளவு',
        'date_time':      'தேதி & நேரம்',
        'clock':          'திரையில் கடிகாரம்',
        'theme':          'தீம்',
        'language':       'மொழி',
        'ip_address':     'போர்டு IP',
        'connect':        'இணை',
        'disconnect':     'துண்டி',
        'name':           'பெயர்',
        'price':          'விலை (₹)',
        'category':       'வகை',
        'welcome':        'வரவேற்கிறோம்',
        'connected':      '🟢 இணைந்தது',
        'not_connected':  '⚪ இணையவில்லை',
        'sent_ok':        'போர்டுக்கு அனுப்பப்பட்டது!',
        'no_board':       '❌ போர்டு இணையவில்லை',
        'scroll_speed':   'உருள் வேகம்',
        'scroll_dir':     'உருள் திசை',
        'text_color':     'எழுத்து நிறம்',
        'bg_color':       'பின்னணி',
        'text_msg':       'செய்தி',
        'quick_msgs':     'விரைவு செய்திகள்',
        'preview':        'முன்னோட்டம்',
    }
}


def s(key):
    from utils.app_state import state
    lang = getattr(state, 'language', 'en')
    return STRINGS.get(lang, STRINGS['en']).get(key, key)
